import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import {auth} from "@/auth"
// import { Session } from "inspector/promises";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/providers/theme-providers";
const poppins=Poppins({
  subsets:["latin"],
  weight:["400","500","600","700"],
  variable:"--font-poppins",
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session= await auth()
  return (
    <SessionProvider session={session}>

    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${poppins.className}antialiased`}
        >
             <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        {/* {children} */}
      </body>
    </html>
        </SessionProvider>
  );
}
